# HW9 Q1

# Step 1 : Plotting data
plot(elecequip)
# It seems some cyclical patterns in data but no clear trend, there is seasonality as well. Series is not stationary

#Step #2 : Decomposing using STL
fit <- stl(elecequip,  s.window="periodic")
plot(fit)
# We clearly see components

#Step #3:
# Yes data has seasonal component, hence creating plot using sasonal adj
fit1 <- seasadj (fit)
plot(fit1)
Acf(fit1)

#Step 4
# Yes there is need to stablize data
lambda = BoxCox.lambda(fit1)
fit2<-BoxCox(fit1,lambda)


#Step 5
plot(fit2)
Acf(fit2)
# Data is not yet stationary

#Step 6
# Running 1st difference
ts_data<- diff(fit2)
plot(ts_data)
Acf(ts_data)
# Now data is stationary

#Step 7
fit <- auto.arima(ts_data)
summary(fit)
# The values of p,d and q are 3,0,1 respectively, AIC=-2007.67

#Step 8
arima(ts_data, order = c(4,0,0)) #aic = -2005.27
arima(ts_data, order = c(3,0,0)) #aic = -2004.54
arima(ts_data, order = c(2,0,0)) #aic = -1989.35
# The best (lowest) AIC was given model generated by auto.arima

#Step 9
res <- residuals(fit)
Acf(res)
Box.test(res, lag=8, fitdf=0)
# Both acf and Box Test confirms that residual is white noise

#Step 10
#Plotting the forecast
plot(forecast(fit))
